/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        AppFooter: typeof import('./components/AppFooter.vue')['default']
        AppNavbar: typeof import('./components/AppNavbar.vue')['default']
        AppSnackbar: typeof import('./components/AppSnackbar.vue')['default']
        ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        UserDetails: typeof import('./components/UserDetails.vue')['default']
        UserForm: typeof import('./components/UserForm.vue')['default']
    }
}
